name: MauliWinterEvent
main: com.mauliwinterevent.MauliWinterEventPlugin
version: 1.0.0
api-version: '1.21'
author: MauliCraft

commands:
  winter:
    description: Hauptbefehl Winter-Event
    aliases: [winterevent, winterzauber, mwe, mauliwinterevent]
    permission: winter.user

  advent:
    description: Adventskalender öffnen
    aliases: [kalender, adventskalender]
    permission: winter.user

  cosmetics:
    description: Cosmetics Menü öffnen
    aliases: [cosmetic, wintercosmetics, wc]
    permission: winter.user

permissions:
  winter.user:
    default: true
  winter.admin:
    default: op
